[package]
name = "engel/mangle"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["aftman.toml","README.md","selene.toml",".luarc"]

[dependencies]
